### ISSUE TITLE
torch compatibility error with model

### ISSUE THREAD

**Issue by mahowak** [vboyce/Maze#14]
I'm getting `AttributeError: 'LSTM' object has no attribute '_flat_weights_names'` when I use the latest torch and there's not an easy way to downgrade to torch < 1.4 since it seems like, for some reason, torch<1.4 is no longer installable through pip.

As far as I can tell, this error can't be fixed without changing the model `hidden650_batch128_dropout0.2_lr20.0.pt` to something that is compatible with modern torch.

Know of any other workarounds?

Thanks for this awesome tool!

**Comment by vboyce** [comment]
For now, I think you do need the right versions of pytorch (1.2.0 or 1.3.1) to work with this model. Conda (https://docs.conda.io/en/latest/) seems willing to install either 1.2 or 1.3, and PyCharm will let me downgrade/install those versions to an environment. 

As a longer term solution, I'll look into whether there are similar models trained in more recent versions of torch that could be used instead.
