### ISSUE TITLE
Maze for French : no model_frwac.pt in french_data

### ISSUE THREAD

**Issue by yanhiz** [vboyce/Maze#20]
Hi,

I am trying to use Maze for French. For English, no problem, but running `./distract.py test_fr.txt ouput_fr.txt -p params_fr.txt` with the French model, I get this error : `No such file or directory: 'french_data/model_frwac.pt'`. Indeed, the french_data folder only contains 'frwac_vocab.txt'. How could I fix that ? I can't see where I can get the 'model_frwac.pt' file. 

Thank you.

**Comment by vboyce** [comment]
Per the setup script, you can get the French model files from https://drive.google.com/drive/folders/19xUZ83f9qcI1PVBdnEv-e6BscWXz_33F

**Comment by yanhiz** [comment]
Thank you so much, it works now!
